"""
tests/test_dashboard_auth.py - Regression tests for CODE_REVIEW H2.

H2: the dashboard shipped with auth off by default and accepted the token via
    query string with a non-constant-time compare. It now:
      - auto-generates a token when none is configured (secure by default),
      - requires it in the Authorization header (never the query string),
      - compares in constant time,
      - refuses to bind to a non-loopback host with no token (fail closed).
"""

from __future__ import annotations

import pytest

from sentinelpi.ui.dashboard import FLASK_AVAILABLE, create_app, _is_loopback

pytestmark = pytest.mark.skipif(not FLASK_AVAILABLE, reason="Flask not installed")


@pytest.fixture
def client(config, db, device_tracker, baseline, alert_manager):
    config.dashboard.access_token = ""  # force the auto-generate path
    app = create_app(config, db, device_tracker, baseline, alert_manager)
    app.config.update(TESTING=True)
    return app.test_client(), config.dashboard.access_token


def test_token_is_autogenerated_when_unset(client):
    _, token = client
    assert token, "an access token should be generated when none is configured"
    assert len(token) >= 20


def test_secret_key_is_not_hardcoded(config, db, device_tracker, baseline, alert_manager):
    app = create_app(config, db, device_tracker, baseline, alert_manager)
    assert app.config["SECRET_KEY"] != "sentinelpi-dashboard-key"
    assert len(app.config["SECRET_KEY"]) >= 32


def test_request_without_token_is_rejected(client):
    c, _ = client
    assert c.get("/api/status").status_code == 401


def test_request_with_wrong_token_is_rejected(client):
    c, _ = client
    resp = c.get("/api/status", headers={"Authorization": "Bearer not-the-token"})
    assert resp.status_code == 401


def test_query_string_token_is_rejected(client):
    """Header only — a token in the query string must not authenticate."""
    c, token = client
    assert c.get(f"/api/status?token={token}").status_code == 401


def test_valid_bearer_token_is_accepted(client):
    c, token = client
    resp = c.get("/api/status", headers={"Authorization": f"Bearer {token}"})
    assert resp.status_code == 200


def test_is_loopback_classification():
    assert _is_loopback("127.0.0.1")
    assert _is_loopback("::1")
    assert _is_loopback("localhost")
    assert not _is_loopback("0.0.0.0")
    assert not _is_loopback("192.168.1.50")


# ---------------------------------------------------------------------------
# Browser login flow (regression for the header-only dead end: a browser can't
# set an Authorization header on navigation, so '/' must lead to a login page,
# and a cookie set there must authenticate both pages and the API).
# ---------------------------------------------------------------------------

def test_unauthenticated_page_redirects_to_login(client):
    c, _ = client
    resp = c.get("/")
    assert resp.status_code == 302
    assert "/login" in resp.headers["Location"]


def test_login_get_serves_form(client):
    c, _ = client
    resp = c.get("/login")
    assert resp.status_code == 200
    assert b"Access token" in resp.data


def test_login_with_wrong_token_is_rejected(client):
    c, _ = client
    resp = c.post("/login", data={"token": "not-the-token"})
    assert resp.status_code == 401
    # No cookie granted → page still gated.
    assert c.get("/").status_code == 302


def test_login_with_valid_token_grants_browser_access(client):
    c, token = client
    # Posting the token in the form body logs in and redirects to the dashboard.
    resp = c.post("/login", data={"token": token})
    assert resp.status_code == 302
    assert resp.headers["Location"] in ("/", "http://localhost/")
    # The session cookie now authenticates the page itself...
    assert c.get("/").status_code == 200
    # ...and the JSON API the page fetches (no Authorization header needed).
    assert c.get("/api/status").status_code == 200


def test_logout_clears_session(client):
    c, token = client
    c.post("/login", data={"token": token})
    assert c.get("/").status_code == 200
    logout = c.get("/logout")
    assert logout.status_code == 302
    assert "/login" in logout.headers["Location"]
    # Cookie cleared → gated again.
    assert c.get("/").status_code == 302


def test_query_string_token_still_rejected_for_pages(client):
    """The old (insecure) ?token= path must not authenticate the page either."""
    c, token = client
    resp = c.get(f"/?token={token}")
    assert resp.status_code == 302
    assert "/login" in resp.headers["Location"]
